services:
  - type: web
    name: smart-room-access-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: GCP_BUCKET_NAME
        sync: false
      - key: GCP_CREDENTIALS
        sync: false
